#!/bin/sh
#
# This file is intended to work on Linux, Mac and Windows.
# Windows support requires that SH.EXE be on the path, and that this script is invoked as
#
#     SH.EXE build <options>
#
# SH.EXE is provided by various things, including Git for Windows.
#
# Note that this script is intentionally limited to POSIX sh, and does not use Bash
# extensions.

set -eu

: "${ODIN:=../Odin/odin}"

OS_NAME="$(uname -s)"
is_windows=""
case "$OS_NAME" in
	MINGW*|MSYS*|CYGWIN*)
		: "${CC:=cl.exe}"
		: "${AR:=lib.exe}"
		is_windows="1"
		;;
	*)
		: "${CC:=cc}"
		: "${AR:=ar}"
		;;
esac


odin_collections=""
odin_options="-thread-count:4 $odin_collections"
check_options="-vet -strict-style -vet-tabs -warnings-as-errors"
test_options="-define:ODIN_TEST_LOG_LEVEL=warning -define:ODIN_TEST_SHORT_LOGS=true -define:ODIN_TEST_THREADS=1"

lib_dirs="
"

exe_dirs="
	src/exe/chat
"

package_dirs="$lib_dirs $exe_dirs"

opt_builds_to_run="$exe_dirs"
opt_checks_to_run="$package_dirs"
opt_tests_to_run="$package_dirs"

run_builds()
{
	# Accepts $@ as extra build flags
	if [ -z "$command_arg" ] || [ "$command_arg" = "all" ]; then
		opt_builds_to_run="$exe_dirs"
	else
		opt_builds_to_run="$command_arg"
	fi
	for dir in $opt_builds_to_run; do
		echo "Building $dir..."
		echo "Options: $@ $odin_options $check_options"
		"$ODIN" build $dir "$@" $odin_options $check_options
	done
}

run_tests()
{
	# Accepts $@ as extra test flags
	if [ -z "$command_arg" ] || [ "$command_arg" = "all" ]; then
		opt_tests_to_run="$package_dirs"
	else
		opt_tests_to_run="$command_arg"
	fi
	for dir in $opt_tests_to_run; do
		echo
		echo "Testing: $dir..."
		echo "Options: $@ $odin_options $check_options $test_options"
		"$ODIN" test $dir "$@" $odin_options $check_options $test_options
	done
}

run_checks() {
	if [ -z "$command_arg" ] || [ "$command_arg" = "all" ]; then
		opt_checks_to_run="$package_dirs"
	else
		opt_checks_to_run="$command_arg"
	fi
	for dir in $opt_checks_to_run; do
		echo "Checking directory $dir..."
		"$ODIN" check $dir $odin_options $check_options -no-entry-point
	done
}

make_etags()
{
	odin_root=$("$ODIN" root)
	tags_files=$(find "$odin_root/core" "$odin_root/base" src -name \*.odin)
	etags						\
	-r '/^\([^ \t]+\)[ \t]+::[ \t]+proc/\1/'	\
	-r '/^\([^ \t]+\)[ \t]+::[ \t]+struct/\1/'	\
	-r '/^\([^ \t]+\)[ \t]+::[ \t]+distinct/\1/'	\
	-r '/^\([^ \t]+\)[ \t]+::[ \t]+enum/\1/'	\
	-r '/^\([^ \t]+\)[ \t]+::[ \t]+union/\1/'	\
	$tags_files
}

build_sqlite3()
{
	# https://sqlite.org/compile.html#recommended_compile_time_options
	# Exceptions:
	#  - THREADSAFE=2 https://sqlite.org/threadsafe.html
	#  - DEFAULT_FOREIGN_KEYS=1
	#  - ENABLE_API_ARMOR: intended to catch development bugs earlier


	sqlite_options="
	-DSQLITE_DQS=0
	-DSQLITE_THREADSAFE=2
	-DSQLITE_DEFAULT_MEMSTATUS=0
	-DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1
	-DSQLITE_LIKE_DOESNT_MATCH_BLOBS
	-DSQLITE_MAX_EXPR_DEPTH=0
	-DSQLITE_OMIT_DECLTYPE
	-DSQLITE_OMIT_DEPRECATED
	-DSQLITE_OMIT_PROGRESS_CALLBACK
	-DSQLITE_OMIT_SHARED_CACHE
	-DSQLITE_OMIT_AUTOINIT
	-DSQLITE_STRICT_SUBTYPE=1
	-DSQLITE_DEFAULT_FOREIGN_KEYS=1
	-DSQLITE_ENABLE_API_ARMOR
	"
	cwd=$(pwd)
	cd src/vendor/sqlite3/sqlite-amalgamation-3530400

	if [ -z "$is_windows" ]; then
		echo "Compiling SQLite3..."
		"$CC" -c -O2 $sqlite_options sqlite3.c
		echo "Creating static library sqlite3.a..."
		"$AR" rcs sqlite3.a sqlite3.o
		echo "Done."
	else
		echo "Compiling SQLite3..."
		"$CC" -nologo -O2 -c $sqlite_options sqlite3.c
		echo "Creating static library sqlite3.lib..."
		"$AR" -nologo sqlite3.obj -out:sqlite3.lib
		echo "Done."
	fi

	cd "$cwd"
}


vendor_sqlite3()
{
	cwd=$(pwd)
	cd src/vendor/sqlite3
	if [ ! -f sqlite-amalgamation-3530400/sqlite3.c ]; then
		echo "Downloading https://sqlite.org/2026/sqlite-amalgamation-3530400.zip..."
		curl -O https://sqlite.org/2026/sqlite-amalgamation-3530400.zip
		echo "Download complete."

		if command -v fossil >/dev/null 2>&1; then
			echo "Verifying checksum..."
			fossil sha3sum sqlite-amalgamation-3530400.zip > downloaded.txt
			if diff checksums.txt downloaded.txt; then
				echo "Checksum verified."
				rm downloaded.txt
			else
				echo "WARNING: sqlite3 checksums do not match!!"
				exit 1
			fi
		else
			echo "WARNING: fossil command not found: Cannot verify checksum!!"
			exit 1
		fi

		unzip -o sqlite-amalgamation-3530400.zip
	else
		echo "Source file exists, skipping download: sqlite-amalgamation-3530400/sqlite3.c"
	fi
	cd "$cwd"
	build_sqlite3
}

clean_sqlite3()
{
	cwd=$(pwd)
	cd src/vendor/sqlite3
	rm -f *.o *.a *.obj *.lib
	cd "$cwd"
}


usage()
{
	if [ -z "$is_windows" ]; then
		echo "Usage: $0 [options] <command> [arg] [-- [command-options]]"
	else
		echo "Usage: SH.EXE $0 [options] <command> [-- [command-options]]"
		echo "       ^^^^^^"
		echo
		echo "Building on Windows requires Git for Windows (for SH.EXE) and MSVC."
	fi
	echo
	echo "Commands:"
	echo "  build [all|directory]   Run all builds, or just a single directory."
	echo "  check [all|directory]   Run all checks, or just a single directory."
	echo "  odin [args]             Run odin CLI with zero or more args"
	echo "  run <directory>         Building and run the executable in directory."
	echo "  tags                    Make emacs etags."
	echo "  test [all|directory]    Run all tests, or just a single directory."
	echo "  vendor sqlite3          Build SQLite3 from source, downloading if needed."
}


if [ $# -eq 0 ]; then
	usage
	exit 1
fi

command=""
command_arg=""

while [ $# -gt 0 ]; do
	case "$1" in
		-h | -help | --help)
			usage
			exit 0
			;;
		--)
			break
			;;

		build)
			command="build"
			;;
		check)
			command="check"
			;;
		clean)
			command="clean"
			;;
		odin)
			command="odin"
			;;
		run)
			command="run"
			;;
		tags)
			command="tags"
			;;
		test)
			command="test"
			;;
		vendor)
			command="vendor"
			;;
		*)
			if [ -n "$command" ] && [ -z "$command_arg" ]; then
				command_arg="$1"
			else
				usage
				exit 1
			fi
	esac
	shift
done

case "$command" in
	build)
		run_builds "$@"
		;;
	check)
		run_checks "$@"
		;;
	clean)
		clean_sqlite3
		;;
	odin)
		"$ODIN" "$command_arg" "$@"
		;;
	run)
		"$ODIN" run "$command_arg" $odin_options $check_options -- "$@"
		;;
	tags)
		make_etags
		;;
	test)
		run_tests "$@"
		;;
	vendor)
		case "$command_arg" in
			sqlite3)
				vendor_sqlite3
				;;
		esac
		;;
esac
